name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grant execute permission to build script
        run: chmod +x ./scripts/build.sh

      - name: Run build script
        run: ./scripts/build.sh

      - name: Grant execute permission to test script
        run: chmod +x ./scripts/test.sh

      - name: Run tests
        run: ./scripts/test.sh
